preferredRoles:
  - Gameplay Programmer
  - Game Developer

preferredEngines:
  - Unreal
  - Unity
  - Godot

preferredWorkModes:
  - Remote
  - Hybrid

preferredLevels:
  - Junior
  - Pleno

preferredLocations:
  - Brasil
  - Canadá
